services:
  alloy-analyzer-service:
    build:
      dockerfile: Dockerfile
    volumes:
#      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
#    command: java -jar /app/AlloyAnalyzerService.jar
#    working_dir: /app